if_show_working_info: true #那些运行中的info正常提示或者什么的,要不要显示

if_simulink: true         ##后面会自动根据是否处于仿真，分配话题
########input_topic_part########配置传感器话题输入部分
odom_end_send_tf: true    #参数默认false，tf统一仅由优化端广播，调试odom_end时设置为true，则只由odom_end广播tf
matching_end_send_tf: false #参数默认false，tf统一仅由优化端广播，调试matching_end时设置为true，则只由matching_end广播tf

imu_topic: /livox/imu
scan_pointcloud_topic: /livox/lidar  #未去畸变原始点云
imu_link: laser_link
lidar_link: laser_link
car_base_link: laser_link                     #仿真车体连结点


sim_imu_topic: /imu
sim_scan_pointcloud_topic: /velodyne_points  #未去畸变原始点云
sim_imu_link: imu
sim_lidar_link: velodyne_base_link
sim_car_base_link: base_link                     #仿真车体连结点



undistorted_pointcloud_topic: /undistorted_points #设定完成去畸变点云的发布话题

base_frame_id:  map                   ##不要有斜杠
########input_topic_part########



registration_method: ICP_SVD # 选择点云匹配方法 目前支持ICP_SVD,ICP,NDT,NDT_CPU(编译没通过),SICP(已有接口，缺少实现)